-- AlterTable
ALTER TABLE "Key" ADD COLUMN     "failApiCall" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "numApiCall" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "successApiCall" INTEGER NOT NULL DEFAULT 0;
